/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  {
    _id: "muGyJEu12A8",
    alt: 'football club videos',
    title: "The NEW & FUTURE Santiago Bernabéu Stadium",
    creator: "Real Madrid",
    videoUrl: 'https://www.youtube.com/watch?v=muGyJEu12A8&list=PLFA93DC971607A2CB&index=1',
    views: '5,050,253 views',
    likes: '134K',
    postedOn: 'Sep 23, 2018',
    type: 'rm',
    avatar: 'https://yt3.ggpht.com/ytc/AKedOLSqx_vKxMzse4ykoG6LtiPKEYkLd8Oh7YydCTMwpqk=s176-c-k-c0x00ffffff-no-rj'
  },
  {
    _id: "5hFd6zGkxLE",
    alt: 'football club videos',
    title: "THANK YOU, CRISTIANO RONALDO | Real Madrid Official Video",
    creator: "Real Madrid",
    videoUrl: 'https://www.youtube.com/watch?v=5hFd6zGkxLE&list=PLFA93DC971607A2CB&index=8',
    views: '47,854,676 views',
    likes: '2.4M',
    postedOn: 'Jul 10, 2018',
    type: 'rm',
    avatar: 'https://yt3.ggpht.com/ytc/AKedOLSqx_vKxMzse4ykoG6LtiPKEYkLd8Oh7YydCTMwpqk=s176-c-k-c0x00ffffff-no-rj'
  },
  {
    _id: "dLdW5SOkao4",
    alt: 'football club videos',
    title: "ZINEDINE ZIDANE | The return of a Real Madrid hero",
    creator: "Real Madrid",
    videoUrl: 'https://www.youtube.com/watch?v=dLdW5SOkao4&list=PLFA93DC971607A2CB&index=13',
    views: '560,416 views',
    likes: '27K',
    postedOn: 'March 12, 2019',
    type: 'rm',
    avatar: 'https://yt3.ggpht.com/ytc/AKedOLSqx_vKxMzse4ykoG6LtiPKEYkLd8Oh7YydCTMwpqk=s176-c-k-c0x00ffffff-no-rj'
  },
  {
    _id: "Yc-7IQqcqeM",
    alt: 'football club videos',
    title: "Hala Madrid...y nada más (feat. RedOne)",
    creator: "Real Madrid",
    videoUrl: 'https://www.youtube.com/watch?v=Yc-7IQqcqeM&list=PLFA93DC971607A2CB&index=60',
    views: '7,912,986 views',
    likes: '232K',
    postedOn: 'May 27, 2014',
    type: 'rm',
    avatar: 'https://yt3.ggpht.com/ytc/AKedOLSqx_vKxMzse4ykoG6LtiPKEYkLd8Oh7YydCTMwpqk=s176-c-k-c0x00ffffff-no-rj'
  },
  {
    _id: "04Q6ybR1bLc",
    alt: 'football club videos',
    title: "Best TACKLES AND BLOCKS | Sergio Ramos x Real Madrid",
    creator: "Real Madrid",
    videoUrl: 'https://www.youtube.com/watch?v=04Q6ybR1bLc&list=PLaI5lCKwq3IcjMspWSu4djRtrrCSC61Ht&index=1',
    views: '452,440 views',
    likes: '17K',
    postedOn: 'June 18, 2021',
    type: 'rm',
    avatar: 'https://yt3.ggpht.com/ytc/AKedOLSqx_vKxMzse4ykoG6LtiPKEYkLd8Oh7YydCTMwpqk=s176-c-k-c0x00ffffff-no-rj'
  },
  {
    _id: "H0GVemJOmIg",
    alt: 'football club videos',
    title: "Sergio Ramos, ALL CHAMPIONS LEAGUE goals | Real Madrid",
    creator: "Real Madrid",
    videoUrl: 'https://www.youtube.com/watch?v=H0GVemJOmIg&list=PLaI5lCKwq3IcjMspWSu4djRtrrCSC61Ht&index=2',
    views: '174,672 views',
    likes: '11K',
    postedOn: 'June 18, 2021',
    type: 'rm',
    avatar: 'https://yt3.ggpht.com/ytc/AKedOLSqx_vKxMzse4ykoG6LtiPKEYkLd8Oh7YydCTMwpqk=s176-c-k-c0x00ffffff-no-rj'
  },
  {
    _id: "X-Dp19wIKhE",
    alt: 'football club videos',
    title: "THANK YOU, SERGIO RAMOS | Real Madrid Legend",
    creator: "Real Madrid",
    videoUrl: 'https://www.youtube.com/watch?v=X-Dp19wIKhE&list=PLaI5lCKwq3IcjMspWSu4djRtrrCSC61Ht&index=5',
    views: '3,124,007 views',
    likes: '244K',
    postedOn: 'June 17, 2021',
    type: 'rm',
    avatar: 'https://yt3.ggpht.com/ytc/AKedOLSqx_vKxMzse4ykoG6LtiPKEYkLd8Oh7YydCTMwpqk=s176-c-k-c0x00ffffff-no-rj'
  },
  {
    _id: "hxzVIiGT_f8",
    alt: 'football club videos',
    title: "REACTION: Reds agree Cristiano Ronaldo deal | Manchester United",
    creator: "Manchester United",
    videoUrl: 'https://www.youtube.com/watch?v=hxzVIiGT_f8&list=PL5-QUghxmluI47lAbIq0F4pSoYdniOMYI&index=4',
    views: '2,327,523 views',
    likes: '123K',
    postedOn: 'August 28, 2021',
    type: 'mu',
    thumbnail: 'https://i.ytimg.com/vi/hxzVIiGT_f8/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA-b7-PC-UF38qC5eRr9F1gtcpLww',
    avatar: 'https://yt3.ggpht.com/jhyv6I72diPw6jNP9LdlQ4GCv6MhOg-s9-q4STT_m3FCRCB8YyMlW-51ozS0ZTDnyg6zzVgT1Q=s176-c-k-c0x00ffffff-no-rj'
  },
  {
    _id: "922h6L3ZjO0",
    alt: 'football club videos',
    title: "Ryan Giggs | Manchester United Greats",
    creator: "Manchester United",
    videoUrl: 'https://www.youtube.com/watch?v=922h6L3ZjO0&list=PL5-QUghxmluKPt9CO9kZ1Y09itF158Z42&index=14',
    views: '166,193 views',
    likes: '5.4K',
    postedOn: 'March 11, 2018',
    type: 'mu',
    thumbnail: 'https://i.ytimg.com/vi/922h6L3ZjO0/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBvz_Xwml38cDqF_5cBydy4HY8BOA',
    avatar: 'https://yt3.ggpht.com/jhyv6I72diPw6jNP9LdlQ4GCv6MhOg-s9-q4STT_m3FCRCB8YyMlW-51ozS0ZTDnyg6zzVgT1Q=s176-c-k-c0x00ffffff-no-rj'
  },
  {
    _id: "2rOKggB6fnQ",
    alt: 'football club videos',
    title: "Paul Scholes | Manchester United Greats",
    creator: "Manchester United",
    videoUrl: 'https://www.youtube.com/watch?v=2rOKggB6fnQ&list=PL5-QUghxmluKPt9CO9kZ1Y09itF158Z42&index=12',
    views: '178,314 views',
    likes: '4.1K',
    postedOn: 'Feb 22, 2018',
    type: 'mu',
    thumbnail: 'https://i.ytimg.com/vi/2rOKggB6fnQ/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBe9QMEIlaUR_DkQJNcqJyf4Yce1g',
    avatar: 'https://yt3.ggpht.com/jhyv6I72diPw6jNP9LdlQ4GCv6MhOg-s9-q4STT_m3FCRCB8YyMlW-51ozS0ZTDnyg6zzVgT1Q=s176-c-k-c0x00ffffff-no-rj'
  },
  {
    _id: "xEfwVQpHLio",
    alt: 'football club videos',
    title: "Ji-sung Park | Manchester United Greats",
    creator: "Manchester United",
    videoUrl: 'https://www.youtube.com/watch?v=xEfwVQpHLio',
    views: '1,134,651 views',
    likes: '29K',
    postedOn: 'May 8, 2018',
    type: 'mu',
    thumbnail: 'https://i.ytimg.com/vi/xEfwVQpHLio/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCgKHWH2hgE1CDHtuv3KLkB5qGMeA',
    avatar: 'https://yt3.ggpht.com/jhyv6I72diPw6jNP9LdlQ4GCv6MhOg-s9-q4STT_m3FCRCB8YyMlW-51ozS0ZTDnyg6zzVgT1Q=s176-c-k-c0x00ffffff-no-rj'
  },
  {
    _id: "BiWafKt68eI",
    alt: 'football club videos',
    title: "David Beckham | Manchester United Greats",
    creator: "Manchester United",
    videoUrl: 'https://www.youtube.com/watch?v=BiWafKt68eI&list=PL5-QUghxmluKPt9CO9kZ1Y09itF158Z42&index=11',
    views: '222,405 views',
    likes: '5.1K',
    postedOn: 'Feb 22, 2018',
    type: 'mu',
    thumbnail: 'https://i.ytimg.com/vi/BiWafKt68eI/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD1HD_u8S9CcN5GxE4HhGqIQkoiJg',
    avatar: 'https://yt3.ggpht.com/jhyv6I72diPw6jNP9LdlQ4GCv6MhOg-s9-q4STT_m3FCRCB8YyMlW-51ozS0ZTDnyg6zzVgT1Q=s176-c-k-c0x00ffffff-no-rj'
  },
  {
    _id: "chq-NNOQV50",
    alt: 'football club videos',
    title: "Ciao, Cristiano! | Juventus says goodbye to Cristiano Ronaldo | Juventus",
    creator: "Juventus",
    videoUrl: 'https://www.youtube.com/watch?v=chq-NNOQV50',
    views: '513,905 views',
    likes: '46K',
    postedOn: 'August 31, 2021',
    type: 'ju',
    thumbnail: 'https://i.ytimg.com/vi/pMuoNqz-LK8/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA1EpcgvJctDmNDcHoX_PzIRg3jVQ',
    avatar: 'https://yt3.ggpht.com/xZbliDrv1hQJOWfLsK29iWa0pQUWTr-1AO-vluYNr_PPCcvoDUog8IMEH4nAKQFdPHdmlwoy=s68-c-k-c0x00ffffff-no-rj'
  },
  {
    _id: "cLfSpFg6Pxg",
    alt: 'football club videos',
    title: "HIGHLIGHTS: Juventus vs Atletico Madrid - 3-0 - Ronaldo hat-trick completes comeback!",
    creator: "Juventus",
    videoUrl: 'https://www.youtube.com/watch?v=cLfSpFg6Pxg',
    views: '11,460,498 views',
    likes: '192K',
    postedOn: 'March 16, 2019',
    type: 'ju',
    thumbnail: 'https://i.ytimg.com/vi/cLfSpFg6Pxg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDNaBd_39KT-jmSGx2deoIQJcmmgQ',
    avatar: 'https://yt3.ggpht.com/xZbliDrv1hQJOWfLsK29iWa0pQUWTr-1AO-vluYNr_PPCcvoDUog8IMEH4nAKQFdPHdmlwoy=s68-c-k-c0x00ffffff-no-rj'
  },
  {
    _id: "p5HFfvkR9t4",
    alt: 'football club videos',
    title: "Cristiano Ronaldo arrives at J|Medical | #CR7DAY | Juventus!",
    creator: "Juventus",
    videoUrl: 'https://www.youtube.com/watch?v=p5HFfvkR9t4',
    views: '3,355,175 views',
    likes: '68K',
    postedOn: 'July 16, 2018',
    type: 'ju',
    thumbnail: 'https://i.ytimg.com/vi/hgB9rLdJDWE/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAaiGr0TF10mbgqwHxHui2k3dhe8A',
    avatar: 'https://yt3.ggpht.com/xZbliDrv1hQJOWfLsK29iWa0pQUWTr-1AO-vluYNr_PPCcvoDUog8IMEH4nAKQFdPHdmlwoy=s68-c-k-c0x00ffffff-no-rj'
  },
  {
    _id: "8PuCoI5H5dQ",
    alt: 'football club videos',
    title: "Juventus Doubles Volley Challenge!",
    creator: "Juventus",
    videoUrl: 'https://www.youtube.com/watch?v=8PuCoI5H5dQ',
    views: '9,535,205 views',
    likes: '62K',
    postedOn: 'August 29, 2018',
    type: 'ju',
    thumbnail: 'https://i.ytimg.com/vi/8PuCoI5H5dQ/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDGGohreY4aNGwuR3O8ViX-xMl3Vw',
    avatar: 'https://yt3.ggpht.com/xZbliDrv1hQJOWfLsK29iWa0pQUWTr-1AO-vluYNr_PPCcvoDUog8IMEH4nAKQFdPHdmlwoy=s68-c-k-c0x00ffffff-no-rj'
  },
  {
    _id: "hh--jwht7Oo",
    alt: 'football club videos',
    title: "The International Juventus Players Check in to Medical | Juventus",
    creator: "Juventus",
    videoUrl: 'https://www.youtube.com/watch?v=hh--jwht7Oo',
    views: '4,614,070 views',
    likes: '46K',
    postedOn: 'July 30, 2018',
    type: 'ju',
    thumbnail: 'https://i.ytimg.com/vi/hh--jwht7Oo/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCio0DqgfikJg9zhbRwyCfo2GwItw',
    avatar: 'https://yt3.ggpht.com/xZbliDrv1hQJOWfLsK29iWa0pQUWTr-1AO-vluYNr_PPCcvoDUog8IMEH4nAKQFdPHdmlwoy=s68-c-k-c0x00ffffff-no-rj'
  },
  {
    _id: "hh--jwht7Oo",
    alt: 'football club videos',
    title: "Lewandowski vs. Müller | Copy the Penalty Challenge",
    creator: "Bayern Munich",
    videoUrl: 'https://www.youtube.com/watch?v=_Q_b-42w7HI',
    views: '16,935,651 views',
    likes: '388K',
    postedOn: 'July 15, 2020',
    type: 'bm',
    thumbnail: 'https://i.ytimg.com/vi/_Q_b-42w7HI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCVMoBat6p07v3ryj9CDDrRllgajA',
    avatar: 'https://yt3.ggpht.com/bUoqRSR8mGhGwTX0rPgsFUNAaDM2yZacgYOoSYtuv21-GXOGeDehD5glMD3S50YOsGYIvgsMWA=s176-c-k-c0x00ffffff-no-rj'
  },
  {
    _id: "hh--jwht7Oo",
    alt: 'football club videos',
    title: "7 Championships, 7 Beer Showers | Best of FC Bayern",
    creator: "Bayern Munich",
    videoUrl: 'https://www.youtube.com/watch?v=l03qv1y4FXs',
    views: '10,811,466 views',
    likes: '94K',
    postedOn: 'May 22, 2019',
    type: 'bm',
    thumbnail: 'https://i.ytimg.com/vi/l03qv1y4FXs/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCPzaIWblaWgULdvmVT39B9lSS_bw',
    avatar: 'https://yt3.ggpht.com/bUoqRSR8mGhGwTX0rPgsFUNAaDM2yZacgYOoSYtuv21-GXOGeDehD5glMD3S50YOsGYIvgsMWA=s176-c-k-c0x00ffffff-no-rj'
  },
  {
    _id: "XE-c0-X5pVA",
    alt: 'football club videos',
    title: "Franck Ribéry's Emotional Goodbye at FC Bayern",
    creator: "Bayern Munich",
    videoUrl: 'https://www.youtube.com/watch?v=XE-c0-X5pVA',
    views: '10,730,397 views',
    likes: '242K',
    postedOn: 'May 21, 2019',
    type: 'bm',
    thumbnail: 'https://i.ytimg.com/vi/XE-c0-X5pVA/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBfEtKRWHRDn7rQOZjsyuumYEMxVA',
    avatar: 'https://yt3.ggpht.com/bUoqRSR8mGhGwTX0rPgsFUNAaDM2yZacgYOoSYtuv21-GXOGeDehD5glMD3S50YOsGYIvgsMWA=s176-c-k-c0x00ffffff-no-rj'
  },
  {
    _id: "poKcrN-VpiM",
    alt: 'football club videos',
    title: "Bayern Challenge feat. Franck Ribéry & Arjen Robben | FC Bayern",
    creator: "Bayern Munich",
    videoUrl: 'https://www.youtube.com/watch?v=poKcrN-VpiM',
    views: '10,207,002 views',
    likes: '158K',
    postedOn: 'May 30, 2019',
    type: 'bm',
    thumbnail: 'https://i.ytimg.com/vi/poKcrN-VpiM/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDUlvyavwSzOfO04823L5Heoik8xA',
    avatar: 'https://yt3.ggpht.com/bUoqRSR8mGhGwTX0rPgsFUNAaDM2yZacgYOoSYtuv21-GXOGeDehD5glMD3S50YOsGYIvgsMWA=s176-c-k-c0x00ffffff-no-rj'
  },
  {
    _id: "2SnX-lRiZzc",
    alt: 'football club videos',
    title: "Manuel Neuer's impressive training at Lake Tegernsee | FC Bayern",
    creator: "Bayern Munich",
    videoUrl: 'https://www.youtube.com/watch?v=2SnX-lRiZzc',
    views: '8,002,005 views',
    likes: '125K',
    postedOn: 'May 6, 2020',
    type: 'bm',
    thumbnail: 'https://i.ytimg.com/vi/2SnX-lRiZzc/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAxoifggg0FWV-te4ejo_mejNo_OQ',
    avatar: 'https://yt3.ggpht.com/bUoqRSR8mGhGwTX0rPgsFUNAaDM2yZacgYOoSYtuv21-GXOGeDehD5glMD3S50YOsGYIvgsMWA=s176-c-k-c0x00ffffff-no-rj'
  },
];
